#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-botocore
Version  : 1.12.128
Release  : 404
URL      : https://github.com/boto/botocore/archive/1.12.128/botocore-1.12.128.tar.gz
Source0  : https://github.com/boto/botocore/archive/1.12.128/botocore-1.12.128.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 LGPL-2.1 MIT
Requires: deprecated-botocore-license = %{version}-%{release}
Requires: deprecated-botocore-python = %{version}-%{release}
Requires: docutils
Requires: jmespath
Requires: jsonschema
Requires: nose
Requires: python-dateutil
Requires: urllib3
Requires: wheel
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3

%description
botocore
========
.. image:: https://secure.travis-ci.org/boto/botocore.png?branch=develop
:target: http://travis-ci.org/boto/botocore

%package legacypython
Summary: legacypython components for the deprecated-botocore package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-botocore package.


%package license
Summary: license components for the deprecated-botocore package.
Group: Default

%description license
license components for the deprecated-botocore package.


%package python
Summary: python components for the deprecated-botocore package.
Group: Default

%description python
python components for the deprecated-botocore package.


%prep
%setup -q -n botocore-1.12.128

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554390653
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
py.test-2.7 || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-botocore
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/deprecated-botocore/LICENSE.txt
cp NOTICE %{buildroot}/usr/share/package-licenses/deprecated-botocore/NOTICE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-botocore/LICENSE.txt
/usr/share/package-licenses/deprecated-botocore/NOTICE

%files python
%defattr(-,root,root,-)
